version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user
    overwrite: true
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      runas: ec2-user
  AfterInstall:
    - location: scripts/update_container.sh
      runas: ec2-user
