
version: 0.2
env:
  parameter-store:
    DOCKER_USERNAME: "/CodeBuild/DOCKER_PASSWORD"
    DOCKER_PASSWORD: "/CodeBuild/DOCKER_USERNAME"
    
phases:
  build:
    commands:
      - echo "Docker Build"
      - docker build -t tiaz0128/docker-react .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker login docker.io -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - docker push tiaz0128/docker-react
      - echo "updated line for codebuild ci"
